algoritmo PassoAPassoAcordar

funcao Acordar()
inicio
    escreva("Escuto o despertador.")
    escreva("Acordo.")
    escreva("Abro os olhos.")
    escreva("Levanto da cama.")
    escreva("Pego o celular.")
    escreva("Desligo o despertador.")
fim_funcao

inicio
    Acordar()
    escreva("Programo o despertador para me acordar novamente em mais 10 minutos.")
    escreva("Deito e durmo.")
    escreva("...10 minutos depois...")
    Acordar()
fim_algoritmo